AWSTemplateFormatVersion: '2010-09-09'
Description:
  create S3

# ------------------------------------------------------------#
# Mappings
# ------------------------------------------------------------#
Mappings:
  S3Config:
    us-east-1:
      BucketPrincipal: '127311923021'
    us-east-2:
      BucketPrincipal: '033677994240'
    us-west-1:
      BucketPrincipal: '027434742980'
    us-west-2:
      BucketPrincipal: '797873946194'
    ca-central-1:
      BucketPrincipal: '985666609251'
    eu-central-1:
      BucketPrincipal: '054676820928'
    eu-west-1:
      BucketPrincipal: '156460612806'
    eu-west-2:
      BucketPrincipal: '652711504416'
    eu-west-3:
      BucketPrincipal: '009996457667'
    eu-north-1:
      BucketPrincipal: '897822967062'
    ap-east-1:
      BucketPrincipal: '754344448648'
    ap-northeast-1:
      BucketPrincipal: '582318560864'
    ap-northeast-2:
      BucketPrincipal: '600734575887'
    ap-northeast-3:
      BucketPrincipal: '383597477331'
    ap-southeast-1:
      BucketPrincipal: '114774131450'
    ap-southeast-2:
      BucketPrincipal: '783225319266'
    ap-south-1:
      BucketPrincipal: '718504428378'
    sa-east-1:
      BucketPrincipal: '507241528517'
    us-gov-west-1:
      BucketPrincipal: '048591011584'
    us-gov-east-1:
      BucketPrincipal: '190560391635'
    cn-north-1:
      BucketPrincipal: '638102146993'
    cn-northwest-1:
      BucketPrincipal: '037604701340'

# ------------------------------------------------------------#
# Resources
# ------------------------------------------------------------#
Resources:

#  S3
# ------------------------------------------------------------#

  S3EXAMPLELOG:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "elblog-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      LifecycleConfiguration:
        Rules:
        - Id: !Sub "LR-elblog-${AWS::AccountId}"
          Status: Enabled
          ExpirationInDays: 1825
          Transitions:
            - StorageClass: GLACIER
              TransitionInDays: 183

# ------------------------------------------------------------#
#  BucketPolicy
# ------------------------------------------------------------#
  S3PLS3EXAMPLELOG:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref 'S3EXAMPLELOG'
      PolicyDocument:
        Id: ElblogsBucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: ALBAccess
            Effect: Allow
            Action:
              - s3:PutObject
            Resource:
              - !Sub 'arn:${AWS::Partition}:s3:::${S3EXAMPLELOG}/*'
            Principal:
              AWS: !FindInMap
                - S3Config
                - !Ref 'AWS::Region'
                - BucketPrincipal


# ------------------------------------------------------------#
# Output Parameters
# ------------------------------------------------------------#
Outputs:
  StackS3EXAMPLELOG:
    Description: "Create S3 elblog ID"
    Value: !Ref "S3EXAMPLELOG"
    Export:
      Name: "S3-ELBLOG"
